source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
install! 'cocoapods', :integrate_targets => true
platform :ios, '8.0'

target 'BTBaseSDK' do
    use_frameworks!

    pod 'Alamofire', '~> 4.7'
    pod 'FMDB'
    pod 'SDWebImage', '~> 4.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'SwiftyStoreKit'
    pod 'MobilePlayer'
    pod 'IQKeyboardManagerSwift'
end

target 'SDKTest' do
    use_frameworks!
    
    pod 'Alamofire', '~> 4.7'
    pod 'FMDB'
    pod 'SDWebImage', '~> 4.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'SwiftyStoreKit'
    pod 'MobilePlayer'
    pod 'IQKeyboardManagerSwift'
end
